openapi: '3.0.2'
info:
  title: Binance SPOT Public API
  description: The swagger file of Binance Public API
  version: '1.0'
servers:
  - url: https://api.binance.com/api/v3
paths:
  /ping:
    get:
      summary: Test Connectivity
      description: Weight 1
      tags:
        - Market Data
      responses:
        '200':
          description: '{}'
  /time:
    get:
      summary: Check Server Time
      description: Weight 1
      tags:
        - Market Data
      responses:
        '200':
          description: Binance server UTC timestamp
          content:
            application/json:
              schema:
                title: server time
                type: object
              example:
                serverTime: 1499827319559
  /exchangeInfo:
    get:
      summary: Exchange Information
      description: Weight 1
      tags:
        - Market Data
      responses:
        '200':
          description: Current exchange trading rules and symbol information
          content:
            application/json:
              schema:
                title: server time
                type: object
              example:
                timezone: UTC
                serverTime: 1592882214236
                rateLimits:
                  - rateLimitType: REQUEST_WEIGHT
                    interval: MINUTE
                    intervalNum: 1
                    limit: 1200
                  - rateLimitType: ORDERS
                    interval: SECOND
                    intervalNum: 10
                    limit: 100
                  - rateLimitType: ORDERS
                    interval: DAY
                    intervalNum: 1
                    limit: 200000
                exchangeFilters: []
                symbols: 
                  - symbol: ETHBTC
                    status: TRADING
                    baseAsset: ETH
                    baseAssetPrecision: 8
                    quoteAsset: BTC
                    quotePrecision: 8
                    quoteAssetPrecision: 8
                    baseCommissionPrecision: 8
                    quoteCommissionPrecision: 8
                    orderTypes: 
                    - LIMIT
                    - LIMIT_MAKER
                    - MARKET
                    - STOP_LOSS_LIMIT
                    - TAKE_PROFIT_LIMIT
                    icebergAllowed: true
                    ocoAllowed: true
                    quoteOrderQtyMarketAllowed: true
                    isSpotTradingAllowed: true
                    isMarginTradingAllowed: true
                    filters: 
                    - filterType: PRICE_FILTER
                      minPrice: "0.00000100"
                      maxPrice: "100000.00000000"
                      tickSize: "0.00000100"
                    - filterType: PERCENT_PRICE
                      multiplierUp: 5
                      multiplierDown: "0.2"
                      avgPriceMins: 5
                    - filterType: LOT_SIZE
                      minQty: "0.00100000"
                      maxQty: "100000.00000000"
                      stepSize: "0.00100000"
                    - filterType: MIN_NOTIONAL
                      minNotional: "0.00010000"
                      applyToMarket: true
                      avgPriceMins: 5
                    - filterType: ICEBERG_PARTS
                      limit: 10
                    - filterType: MARKET_LOT_SIZE
                      minQty: "0.00000000"
                      maxQty: "10837.63823875"
                      stepSize: "0.00000000"
                    - filterType: MAX_NUM_ALGO_ORDERS
                      maxNumAlgoOrders: 5
                    - filterType: MAX_NUM_ORDERS
                      maxNumOrders: 200
                    permissions: 
                    - SPOT
                    - MARGIN
  /depth:
    get:
      summary: Order Book
      description: Weight 1
      tags:
        - Market Data
      parameters:
        - name: symbol
          in: query
          required: true
          description: trading symbol, e.g. BTCUSDT
          schema:
            type: string
        - name: limit
          in: query
          description: Default 100; max 1000. Valid limits:[5, 10, 20, 50, 100, 500, 1000, 5000]
          schema:
            type: integer           
      responses:
        '200':
          description: Binance server UTC timestamp
          content:
            application/json:
              schema:
                title: server time
                type: object
              example:
                lastUpdateId: 1060776800
                bids: 
                - 
                  - "16.39580000"
                  - "19.41000000"
                - 
                  - "16.39450000"
                  -  "1.00000000"
                asks: 
                - 
                  - "16.39790000"
                  -  "25.48000000"
                - 
                  -  "16.39800000"
                  -  "5.57000000"
  /trades:
    get:
      summary: Recent Trades List
      description: Get recent trades (up to last 500).
        <br/> Weight 1
      tags:
        - Market Data
      parameters:
        - name: symbol
          in: query
          required: true
          description: trading symbol, e.g. BTCUSDT
          schema:
            type: string
        - name: limit
          in: query
          description: Default 100; max 1000. Valid limits:[5, 10, 20, 50, 100, 500, 1000, 5000]
          schema:
            type: integer           
      responses:
        '200':
          description: Binance server UTC timestamp
          content:
            application/json:
              schema:
                title: server time
                type: object
              example:
                lastUpdateId: 1060776800
                bids: 
                - 
                  - "16.39580000"
                  - "19.41000000"
                - 
                  - "16.39450000"
                  -  "1.00000000"
                asks: 
                - 
                  - "16.39790000"
                  -  "25.48000000"
                - 
                  -  "16.39800000"
                  -  "5.57000000"
